/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.polarsys.capella.scenario.editor.dslscenario.ui.AbstractDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  public DslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
