/*
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.validation

import org.eclipse.xtext.validation.Check
import org.polarsys.capella.scenario.editor.dslscenario.dsl.Actor
import org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage
import org.polarsys.capella.scenario.editor.helper.EmbeddedEditorInstanceHelper

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DslValidator extends AbstractDslValidator {

	public static val INVALID_NAME = 'invalidName'
	
	@Check
	def checkActor(Actor actor) {
		if (!EmbeddedEditorInstanceHelper.getAvailableInstanceRolesName().contains(actor.name)) {
			error('Instance role not exist', DslPackage.Literals.ACTOR__NAME, INVALID_NAME)
		}
	}
}
