/*
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.validation

import org.eclipse.xtext.validation.Check
import org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage
import org.polarsys.capella.scenario.editor.helper.EmbeddedEditorInstanceHelper
import org.polarsys.capella.scenario.editor.dslscenario.dsl.Participant
import org.polarsys.capella.scenario.editor.dslscenario.dsl.Function
import org.polarsys.capella.scenario.editor.dslscenario.dsl.Message
import org.polarsys.capella.scenario.editor.dslscenario.dsl.SequenceMessage

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DslValidator extends AbstractDslValidator {

	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkPartExists(Participant participant) {
		if (!EmbeddedEditorInstanceHelper.getAvailablePartNames(participant.keyword).contains(participant.name)) {
			if (participant instanceof Function) {
				error('Function does not exist', DslPackage.Literals.PARTICIPANT__NAME, INVALID_NAME)
			} else {
				error('Represented part does not exist', DslPackage.Literals.PARTICIPANT__NAME, INVALID_NAME)
			}
		}
	}

	@Check
	def checkParticipantKeywordIsValid(Participant participant) {
		if (!EmbeddedEditorInstanceHelper.checkValidKeyword(participant.keyword)) {
			error('\'' + participant.keyword + '\' could not be used in this diagram',
				DslPackage.Literals.PARTICIPANT__KEYWORD)
		}
	}
	
	@Check
	def checkMessagesExist(SequenceMessage message) {
		if (!EmbeddedEditorInstanceHelper.getMessageSequenceName(message.getSource, message.getTarget).contains(message.name)) {
			error('Message does not exist', DslPackage.Literals.MESSAGE__NAME)
		}
	}
}
