/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Type And Participants</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.ScenarioTypeAndParticipants#getName <em>Name</em>}</li>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.ScenarioTypeAndParticipants#getParticipants <em>Participants</em>}</li>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.ScenarioTypeAndParticipants#getParticipant <em>Participant</em>}</li>
 * </ul>
 *
 * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getScenarioTypeAndParticipants()
 * @model
 * @generated
 */
public interface ScenarioTypeAndParticipants extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getScenarioTypeAndParticipants_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.ScenarioTypeAndParticipants#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Participants</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participants</em>' containment reference list.
   * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getScenarioTypeAndParticipants_Participants()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getParticipants();

  /**
   * Returns the value of the '<em><b>Participant</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participant</em>' containment reference list.
   * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getScenarioTypeAndParticipants_Participant()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getParticipant();

} // ScenarioTypeAndParticipants
