/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.ParticipantDeactivation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Participant Deactivation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ParticipantDeactivationImpl extends MessageImpl implements ParticipantDeactivation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParticipantDeactivationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.PARTICIPANT_DEACTIVATION;
  }

} //ParticipantDeactivationImpl
