/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.ScenarioTypeAndParticipants;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scenario Type And Participants</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.impl.ScenarioTypeAndParticipantsImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.impl.ScenarioTypeAndParticipantsImpl#getParticipants <em>Participants</em>}</li>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.impl.ScenarioTypeAndParticipantsImpl#getParticipant <em>Participant</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ScenarioTypeAndParticipantsImpl extends MinimalEObjectImpl.Container implements ScenarioTypeAndParticipants
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParticipants() <em>Participants</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParticipants()
   * @generated
   * @ordered
   */
  protected EList<EObject> participants;

  /**
   * The cached value of the '{@link #getParticipant() <em>Participant</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParticipant()
   * @generated
   * @ordered
   */
  protected EList<EObject> participant;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScenarioTypeAndParticipantsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.SCENARIO_TYPE_AND_PARTICIPANTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EObject> getParticipants()
  {
    if (participants == null)
    {
      participants = new EObjectContainmentEList<EObject>(EObject.class, this, DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANTS);
    }
    return participants;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EObject> getParticipant()
  {
    if (participant == null)
    {
      participant = new EObjectContainmentEList<EObject>(EObject.class, this, DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANT);
    }
    return participant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANTS:
        return ((InternalEList<?>)getParticipants()).basicRemove(otherEnd, msgs);
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANT:
        return ((InternalEList<?>)getParticipant()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__NAME:
        return getName();
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANTS:
        return getParticipants();
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANT:
        return getParticipant();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__NAME:
        setName((String)newValue);
        return;
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANTS:
        getParticipants().clear();
        getParticipants().addAll((Collection<? extends EObject>)newValue);
        return;
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANT:
        getParticipant().clear();
        getParticipant().addAll((Collection<? extends EObject>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANTS:
        getParticipants().clear();
        return;
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANT:
        getParticipant().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANTS:
        return participants != null && !participants.isEmpty();
      case DslPackage.SCENARIO_TYPE_AND_PARTICIPANTS__PARTICIPANT:
        return participant != null && !participant.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ScenarioTypeAndParticipantsImpl
