/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.formatter;

import com.google.inject.Inject;
import java.util.Arrays;
import java.util.function.Consumer;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.Actor;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.Model;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.ScenarioTypeAndParticipants;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.SequenceMessage;
import org.polarsys.capella.scenario.editor.dslscenario.services.DslGrammarAccess;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DslGrammarAccess _dslGrammarAccess;
  
  protected void _format(final Model it, @Extension final IFormattableDocument document) {
    final ISemanticRegion begin = this.textRegionExtensions.regionFor(it).keyword("scenario");
    final ISemanticRegion end = this.textRegionExtensions.regionFor(it).keyword("}");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it_1) -> {
      it_1.noSpace();
    };
    document.prepend(begin, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it_1) -> {
      it_1.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(begin, end, _function_1);
    document.<ScenarioTypeAndParticipants>format(it.getScenarioType());
    final Consumer<EObject> _function_2 = (EObject element) -> {
      document.<EObject>format(element);
    };
    it.getMessagesOrReferences().forEach(_function_2);
  }
  
  protected void _format(final ScenarioTypeAndParticipants scenarioType, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(scenarioType).keyword("{"), _function);
    final Consumer<EObject> _function_1 = (EObject it) -> {
      document.<EObject>format(it);
    };
    scenarioType.getParticipants().forEach(_function_1);
  }
  
  protected void _format(final Actor actor, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(actor).keyword("actor"), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(actor).feature(DslPackage.Literals.ACTOR__ID), _function_1);
  }
  
  protected void _format(final SequenceMessage message, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(message).feature(DslPackage.Literals.MESSAGE__NAME), _function);
  }
  
  public void format(final Object message, final IFormattableDocument document) {
    if (message instanceof XtextResource) {
      _format((XtextResource)message, document);
      return;
    } else if (message instanceof SequenceMessage) {
      _format((SequenceMessage)message, document);
      return;
    } else if (message instanceof Actor) {
      _format((Actor)message, document);
      return;
    } else if (message instanceof Model) {
      _format((Model)message, document);
      return;
    } else if (message instanceof ScenarioTypeAndParticipants) {
      _format((ScenarioTypeAndParticipants)message, document);
      return;
    } else if (message instanceof EObject) {
      _format((EObject)message, document);
      return;
    } else if (message == null) {
      _format((Void)null, document);
      return;
    } else if (message != null) {
      _format(message, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(message, document).toString());
    }
  }
}
